# Generated by Django 5.2.13 on 2026-04-09 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.JSONField(default=list, help_text='List of {role, text, timestamp} message objects')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of what was practiced')),
                ('corrections', models.JSONField(default=list, help_text='List of {original, corrected, explanation} objects')),
                ('pronunciation_score', models.FloatField(blank=True, help_text='Overall pronunciation score 0–100', null=True)),
                ('fluency_score', models.FloatField(blank=True, help_text='Fluency score 0–100', null=True)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('scenario', models.CharField(blank=True, help_text="e.g. 'Ordering food at a Parisian café'", max_length=300)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.language')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='voice_voice_user_id_a1250f_idx')],
            },
        ),
    ]
