# Generated by Django 5.2.13 on 2026-04-09 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(default='🌐', max_length=10)),
                ('tts_locale', models.CharField(default='fr-FR', help_text="BCP-47 locale for SpeechSynthesis API, e.g. 'fr-FR'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('greetings', 'Greetings & Introductions'), ('food_drink', 'Food & Drink'), ('travel', 'Travel'), ('grammar', 'Grammar Basics'), ('roleplay', 'Role-play Scenarios'), ('culture', 'Culture & Customs'), ('business', 'Business French'), ('numbers', 'Numbers & Time'), ('family', 'Family & Relationships'), ('shopping', 'Shopping'), ('health', 'Health & Body'), ('nature', 'Nature & Weather')], max_length=50)),
                ('difficulty', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Mastery')], default='A1', max_length=2)),
                ('content', models.JSONField(default=dict)),
                ('audio_script', models.TextField(blank=True, help_text='Script used for TTS practice — key phrases to speak aloud.')),
                ('scenario_prompt', models.TextField(blank=True, help_text='System prompt used when the user practices this lesson via voice chat.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=10)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('thumbnail_emoji', models.CharField(default='📚', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True, help_text='Free preview lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.language')),
            ],
            options={
                'ordering': ['language', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, help_text='Score 0–100')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('first_attempted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_practiced_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-last_practiced_at'],
            },
        ),
    ]
